---
name: Integration tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  integration_tests:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v2
        with:
          path: ~/.tox
          key: poetry-${{ hashFiles('poetry.lock') }}

      - run: 'poetry run pytest -vv -n auto'
